exportdefaultfunctiongetFullResponseFromAPI(success){
returnnewpromise((resolve,reject)=>{
if(success=True){
resolve({status:200,body:'Success'});
}else{
reject(newError('ThefakeAPIisnotworkingcurrently'));
}
});
}
